backend:
  name: github
  repo: DanielCarlyle/cjfilms
  branch: master
  site_domain: cjmfilms.netlify.app


media_folder: "img/clients"

collections:
  - name: "home-page-video"
    label: "Home Page Video"
    files:
      - label: "home page video settings"
        name: "site"
        file: "_data/site.yml"     
        fields: 
          -  label: "Video"
             name: "front_page_video"
             widget: "text"
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"     
        fields: 
          -  label: "Bio Description"
             name: "bio_description"
             widget: "text"
